### ISSUE TITLE
Issue with prototype for function FT891_CAT::GetTX ()	

### ISSUE THREAD

**Issue by Fnord666b** [WA2FZW/An-FT-891-CAT-Control-Emulator-Library-by-WA2FZW#2]
Function FT891_CAT::GetTX () is defined as returning uint8_t in the source file FT891_CAT.cpp but it is defined as returning bool in the header file FT891_CAT.h.  This results in compile failures.

In addition the example code may need to be updated with the change in return type for this function.

**Comment by WA2FZW** [comment]
I thought I had fixed this several months ago! Apparently not! It is fixed now.

The demo program is fine as it only checks to see if the transmitter is on or off. It doesn't care whether it's on due to the PTT or CAT control.

Issue closed.
